#!/usr/bin/env python3
"""Generate missing display and pipeline stage images for XenoProjection.

PER EXPERIMENT (MorphoVignette / GlyphVignette display images):
    {uid}_ann_N.png  – AE output colorized black/white, fit-in-circle
    {uid}_bio_N.png  – color perspective-corrected source, fit-in-circle

PER SNAPSHOT (PipelineVignette stage images):
    *_raw_col.png    – color perspective-corrected source
    *_raw_bsb.png    – color minus base image (natural-scale base subtraction)
    *_raw_4prj.png   – postprocessed AE output (postprocess_output + squircle)

Usage:
    python xeno_generate_display_images.py XenoPi/snapshots/
    python xeno_generate_display_images.py XenoPi/snapshots/ --force
    python xeno_generate_display_images.py XenoPi/snapshots/ --min-year 2025
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

import xeno_image
from xeno_video import experiment_to_gif


# ---------------------------------------------------------------------------
# Settings helpers
# ---------------------------------------------------------------------------

def _load_settings(exp_dir, global_cfg=None):
    """Return settings dict for an experiment directory.

    Tries the experiment's own settings.json first, then falls back to the
    global config passed on the command line.
    """
    local = exp_dir / "settings.json"
    if local.exists():
        with open(local) as f:
            return json.load(f)
    if global_cfg:
        return global_cfg
    return None


# ---------------------------------------------------------------------------
# Per-experiment display images  (_ann_N / _bio_N)
# ---------------------------------------------------------------------------

def _has_display_images(exp_dir):
    uid = exp_dir.name
    return (
        len(list(exp_dir.glob(f"{uid}_ann_*.png"))) > 0 and
        len(list(exp_dir.glob(f"{uid}_bio_*.png"))) > 0
    )


def _can_generate_display(exp_dir):
    has_ann = (len(list(exp_dir.glob("*_4prj.png"))) > 0 or
               len(list(exp_dir.glob("*_3ann.png"))) > 0)
    return (
        len(list(exp_dir.glob("*_raw.png"))) > 0 and
        has_ann and
        (exp_dir / "base_image.png").exists() and
        (exp_dir / "settings.json").exists()
    )


def generate_display_images(exp_dir, force=False):
    """Generate {uid}_ann_N.png and {uid}_bio_N.png.  Returns (n_ann, n_bio)."""
    uid = exp_dir.name
    ann_pattern = str(exp_dir / f"{uid}_ann_%d.png")
    bio_pattern = str(exp_dir / f"{uid}_bio_%d.png")
    experiment_to_gif(
        str(exp_dir), ann_pattern, "ann_all",
        fit_in_circle=True,
        ann_background=(0, 0, 0),
        ann_foreground=(255, 255, 255),
    )
    experiment_to_gif(str(exp_dir), bio_pattern, "bio_all", fit_in_circle=True)
    return (
        len(list(exp_dir.glob(f"{uid}_ann_*.png"))),
        len(list(exp_dir.glob(f"{uid}_bio_*.png"))),
    )


# ---------------------------------------------------------------------------
# Per-snapshot pipeline stage images  (_col / _bsb / _4prj)
# ---------------------------------------------------------------------------

def _missing_pipeline_stages(exp_dir):
    """Count raw snapshots that are missing at least one pipeline stage file."""
    missing = 0
    for raw in sorted(exp_dir.glob("*_raw.png")):
        stem = raw.stem
        if not (raw.with_name(stem + "_col.png").exists() and
                raw.with_name(stem + "_bsb.png").exists() and
                raw.with_name(stem + "_4prj.png").exists()):
            missing += 1
    return missing


def generate_pipeline_snapshots(exp_dir, settings, force=False):
    """Generate _raw_col.png, _raw_bsb.png, and _raw_4prj.png per snapshot.

    _4prj is generated by applying postprocess_output() to _3ann (raw AE
    output), matching what xeno_osc.py does at runtime.

    Returns count of snapshots processed.
    """
    input_quad   = tuple(settings["camera_quad"])
    base_path    = exp_dir / "base_image.png"
    base_img     = Image.open(str(base_path)) if base_path.exists() else None

    # Postprocessing parameters (same defaults as xeno_osc.py).
    output_size         = int(settings.get("output_size",         224))
    output_stroke_width = int(settings.get("output_stroke_width", 20))
    output_boundary_px  = int(settings.get("output_boundary_px",  22))
    output_threshold    = float(settings.get("output_threshold",  0.5))
    output_area_max     = settings.get("output_area_max", None)
    if output_area_max is not None:
        output_area_max = float(output_area_max)
    squircle_mode = str(settings.get("squircle_mode", "none"))
    if squircle_mode == "none" and settings.get("use_squircle", False):
        squircle_mode = "inside"

    raw_files = sorted(exp_dir.glob("*_raw.png"))
    n_done = 0

    for raw_path in raw_files:
        stem     = raw_path.stem
        col_path = raw_path.with_name(stem + "_col.png")
        bsb_path = raw_path.with_name(stem + "_bsb.png")
        prj_path = raw_path.with_name(stem + "_4prj.png")
        ann_path = raw_path.with_name(stem + "_3ann.png")

        needs_col = force or not col_path.exists()
        needs_bsb = force or not bsb_path.exists()
        needs_prj = (force or not prj_path.exists()) and ann_path.exists()

        if not (needs_col or needs_bsb or needs_prj):
            continue

        raw_img = Image.open(str(raw_path))

        # col: color perspective-corrected
        col_img = xeno_image.transform(raw_img.convert("RGB"), input_quad)
        if needs_col:
            col_img.save(str(col_path))

        # bsb: color minus base (grayscale, natural scale)
        if needs_bsb and base_img is not None:
            base_tf = xeno_image.transform(base_img.convert("L"), input_quad)
            xeno_image.remove_base_natural(col_img, base_tf).save(str(bsb_path))

        # 4prj: postprocess _3ann (raw AE output) the same way xeno_osc.py does.
        if needs_prj:
            prj_img = xeno_image.postprocess_output(
                Image.open(str(ann_path)),
                output_size=output_size,
                threshold=output_threshold,
                stroke_width=output_stroke_width,
                boundary_px=output_boundary_px,
                area_max=output_area_max,
            )
            if squircle_mode == "inside":
                prj_img = xeno_image.to_circle_inside(prj_img)
            elif squircle_mode == "outside":
                prj_img = xeno_image.to_circle_outside(prj_img)
            prj_img.save(str(prj_path))

        n_done += 1

    return n_done


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=__doc__,
    )
    parser.add_argument("directory",
                        help="Root snapshots directory to scan")
    parser.add_argument("-C", "--configuration-file", default=None,
                        help="Global settings.json fallback (used when experiment has none)")
    parser.add_argument("--force", action="store_true",
                        help="Regenerate all images even if they already exist")
    parser.add_argument("--min-year", type=int, default=2023,
                        help="Skip directories whose name starts with a year earlier than this")
    parser.add_argument("--skip-display", action="store_true",
                        help="Skip generating {uid}_ann / _bio display images")
    parser.add_argument("--skip-pipeline", action="store_true",
                        help="Skip generating per-snapshot _col / _bsb / _net images")
    args = parser.parse_args()

    # Load optional global config.
    global_cfg = None
    if args.configuration_file:
        with open(args.configuration_file) as f:
            global_cfg = json.load(f)

    # Collect experiment directories.
    root = Path(args.directory)
    exp_dirs = sorted([
        d for d in root.iterdir()
        if d.is_dir()
        and d.name[:4].isdigit()
        and int(d.name[:4]) >= args.min_year
        and d.name != "trash"
    ])

    if not exp_dirs:
        print(f"No experiment directories found in {root}", file=sys.stderr)
        sys.exit(1)

    total = len(exp_dirs)
    stats = {"display": 0, "pipeline": 0, "skipped": 0, "errors": 0}

    for i, exp_dir in enumerate(exp_dirs, 1):
        uid    = exp_dir.name
        prefix = f"[{i:3d}/{total}] {uid}"
        parts  = []

        # --- display images ---
        if not args.skip_display:
            if not _can_generate_display(exp_dir):
                parts.append("no raw/3ann/base/settings")
            elif not args.force and _has_display_images(exp_dir):
                parts.append("display:ok")
            else:
                try:
                    n_ann, n_bio = generate_display_images(exp_dir, args.force)
                    parts.append(f"display:{n_ann}ann+{n_bio}bio")
                    stats["display"] += 1
                except Exception as e:
                    parts.append(f"display:ERROR({e})")
                    stats["errors"] += 1

        # --- pipeline snapshot images ---
        if not args.skip_pipeline:
            settings = _load_settings(exp_dir, global_cfg)
            if settings is None:
                parts.append("pipeline:no-settings")
            else:
                missing = _missing_pipeline_stages(exp_dir)
                if not args.force and missing == 0:
                    parts.append("pipeline:ok")
                else:
                    try:
                        n = generate_pipeline_snapshots(exp_dir, settings, args.force)
                        parts.append(f"pipeline:{n}snaps")
                        if n > 0:
                            stats["pipeline"] += 1
                    except Exception as e:
                        parts.append(f"pipeline:ERROR({e})")
                        stats["errors"] += 1

        all_ok = all(p.endswith(":ok") or p.endswith(":no-settings") or p.endswith("no raw/3ann/base/settings") for p in parts)
        if all_ok:
            stats["skipped"] += 1
        print(f"{prefix}: {', '.join(parts)}")

    print(f"\nDone: {stats['display']} display, {stats['pipeline']} pipeline, "
          f"{stats['skipped']} fully skipped, {stats['errors']} errors.")
